install-files/usr/*		/usr/
install-files/etc/*		/etc/
install-files/service/* /lib/systemd/system/
setup-gui/interface.glade	/usr/share/lliurex-openmeetings/setup-rsrc/
setup-gui/rsrc	/usr/share/lliurex-openmeetings/
service-gui/interface.glade	/usr/share/lliurex-openmeetings/service-rsrc/
service-gui/lliurex-openmeetings-service-gui	/usr/sbin
setup-gui/lliurex-openmeetings-setup-qt.py	/usr/sbin

