Name=LliurexMeet setup
Name[en]=LliurexMeet setup
Name[es]=Configuración de LliurexMeet
Name[qcv]=Configurar el LliurexMeet
Name[ca_ES]=Configurar el LliurexMeet
Comment=Setup the database or configure OpenMeetings
Comment[en]=Setup the database or configure OpenMeetings
Comment[es]=Interfaz de configuración de la base de datos y el servicio de OpenMeetings 
Comment[qcv]=Interficie de configuració de la base de datos i el servei del OpenMeetings
Comment[ca_ES]=Interficie de configuració de la base de datos i el servei del OpenMeetings
Icon=lliurexmeet
Category=Services
ScriptPath=lliurex-openmeetings-service.zmd
Groups=sudo;admins;teachers
Using=pkexec
Depends=lliurex-openmeetings
